Adding orm
nilenso/dhobi-seva-android pull request #10
Opened 2017-03-03 02:17 UTC by ManishaRana1195

This helps in
1. being able to create and query tables with the help of ORM
2. beind able to manage migrations

2017-03-08 12:28 UTC, deobald requested changes
Make sure PR is atomic; bring fixes to ORM stuff in here.

2017-03-08 12:28 UTC, deobald commented on app/src/main/java/com/geekskool/dhobi/VipasnaApplication.java
> +public class VipasnaApplication extends Application {
"vipassana"

2017-03-08 12:28 UTC, deobald commented on app/src/main/java/com/geekskool/dhobi/VipasnaApplication.java
> +                .schemaVersion(1)
schema version = 0

2017-03-09 04:17 UTC, ManishaRana1195 commented
1. Did the requested changes.
2. Providing this [link](https://realm.io/docs/java/latest/#closing-realm-instances) and [this](https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances), implying that realm instances are not singleton.

2017-03-10 11:05 UTC, ManishaRana1195 commented
This pull request is associated with replacing the underlying SQlite Db with Realm.

2017-03-10 11:05 UTC, merged